# This is the default base file to config env and command
# Notice that chaincode is executed inside docker in default net mode

# Depends on the yeasy/hyperledger-peer:pbft image

# This utilized the pbft as consensus
# See https://github.com/hyperledger/fabric/blob/master/docs/dev-setup/devnet-setup.md#using-consensus-plugin for more details.

vp:
  image: hyperledger/fabric-peer:latest
  restart: unless-stopped
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_PEER_NETWORKID=dev
    - CORE_LOGGING_LEVEL=info  #critical, error, warning, notice, info, debug
    # The following section enables pbft consensus
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
    - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
    - CORE_PBFT_GENERAL_TIMEOUT_NULLREQUEST=4s
  expose:
    - "7050"
    - "7051"
    - "7052"
    - "7053"
  volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
    - /var/run/docker.sock:/var/run/docker.sock
  command: sh -c "sleep 20; peer node start "  # this repeats the default cmd to make sure
